config/routes.rb
Rails.application.routes.draw do
  resources :expenses

  devise_for :users
  get 'home/index'

  root to: "home#index"

end

app/models/budgets.rb
class Budgets < ActiveRecord::Base
  belongs_to :user
end

app/models/expense.rb
class Expense < ActiveRecord::Base
  belongs_to :user
end

app/models/expense_type.rb
class ExpenseType < ActiveRecord::Base
  belongs_to :expenses
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :budgets
  has_many :expenses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?
  hide_action :current_user

  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.for(:account_update) do |u|
      u.permit(:first_name, :last_name ,:email, :password, :password_confirmation, :current_password, :budget)
    end
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_expense, only: [:show, :edit, :update, :destroy]

  # GET /expenses
  # GET /expenses.json
  def index
    @expenses = Expense.all
  end

  # GET /expenses/1
  # GET /expenses/1.json
  def show
  end

  # GET /expenses/new
  def new
    @expense = Expense.new
  end

  # GET /expenses/1/edit
  def edit
  end

  # POST /expenses
  # POST /expenses.json
  def create
    @expense = Expense.new(expense_params)

    respond_to do |format|
      if @expense.save
        format.html { redirect_to @expense, notice: 'Expense was successfully created.' }
        format.json { render :show, status: :created, location: @expense }
      else
        format.html { render :new }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expenses/1
  # PATCH/PUT /expenses/1.json
  def update
    respond_to do |format|
      if @expense.update(expense_params)
        format.html { redirect_to @expense, notice: 'Expense was successfully updated.' }
        format.json { render :show, status: :ok, location: @expense }
      else
        format.html { render :edit }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1
  # DELETE /expenses/1.json
  def destroy
    @expense.destroy
    respond_to do |format|
      format.html { redirect_to expenses_url, notice: 'Expense was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expense
      @expense = Expense.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def expense_params
      params.require(:expense).permit(:user_id, :expense_type_id, :amount)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    unless user_signed_in?
      redirect_to new_user_session_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/expenses/_form.html.slim
= form_for @expense do |f|
  - if @expense.errors.any?
    #error_explanation
      h2 = "#{pluralize(@expense.errors.count, "error")} prohibited this expense from being saved:"
      ul
        - @expense.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :user_id
    = f.number_field :user_id
  .field
    = f.label :expense_type_id
    = f.number_field :expense_type_id
  .field
    = f.label :amount
    = f.text_field :amount
  .actions = f.submit 'Save'

app/views/expenses/edit.html.slim
h1 Editing expense

== render 'form'

= link_to 'Show', @expense
'|
= link_to 'Back', expenses_path

app/views/expenses/index.html.slim
h1 Listing expenses

table
  thead
    tr
      th User
      th Expense type
      th Amount
      th
      th
      th

  tbody
    - @expenses.each do |expense|
      tr
        td = expense.user_id
        td = expense.expense_type_id
        td = expense.amount
        td = link_to 'Show', expense
        td = link_to 'Edit', edit_expense_path(expense)
        td = link_to 'Destroy', expense, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Expense', new_expense_path

app/views/expenses/new.html.slim
h1 New expense

== render 'form'

= link_to 'Back', expenses_path

app/views/expenses/show.html.slim
p#notice = notice

p
  strong User:
  = @expense.user_id
p
  strong Expense type:
  = @expense.expense_type_id
p
  strong Amount:
  = @expense.amount

= link_to 'Edit', edit_expense_path(@expense)
'|
= link_to 'Back', expenses_path

app/views/home/index.html.slim
= render 'home/setup_budget'

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1.0"

    title == content_for?(:title) ? yield(:title) : "Untitled"

  = stylesheet_link_tag "application"
  = javascript_include_tag "vendor/modernizr"
  = csrf_meta_tag

body
  p.notice= notice
  p.alert= alert
  == yield

  = javascript_include_tag "application"